config/routes.rb
Rails.application.routes.draw do
  resources :users
  delete '/user-avatar/:id' => 'user_avatars#destroy', as: :user_avatar
  root to: 'home#index'
  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_confirmation_of :password
  before_create :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def logged_in?
    if  session[:user_id]
      @current_user ||= User.find(session[:user_id])
      @current_user = true
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && User.authenticate(params[:email], params[:password])
      flash[:notice] = "Successfully logged in"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "User name or password entered incorrectly."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/user_avatars_controller.rb
class UserAvatarsController < ApplicationController
  def destroy
    @user = User.find(params[:id])
    @user.avatar = nil
    @user.save
    flash[:alert] = "Avatar Destroyed!"
    redirect_to user_path(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      User.authenticate(params[:email], params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the site!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update # parameters should look like { :user => { :avatar => nil } }
    @user = User.find(params[:id])
    if @user.update(user_params)
      if user_params[:avatar].blank?
        @user.avatar = nil
        @user.save
        binding.pry
      end
      flash[:notice]="You have successfully updated #{@user.email}!"
      redirect_to user_path(@user)
    # elsif link("Delete Avatar").click
    #   @user.update(:avatar => nil)
    #   @user.avatar.save
    #   flash[:notice]="Avatar Destroyed!"
    #   redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      flash[:alert] = "Account destroyed!"
      redirect_to '/'
    else
      flash[:alert] = "There was a problem deleting your account. Please try again."
      redirect_to '/'
    end
  end




  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= render('shared/header', title: 'Welcome') %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">

    <% if logged_in? %>
    <li><%= link_to 'Your Page', user_path %></li>
    <li><%= link_to 'Account Settings', edit_user_path %></li>
    <li><%= link_to 'Logout', log_out_path %></li>

    <% else %>
    <li><%= link_to "Login", log_in_path %></li>
    <li><%= link_to "Sign Up", new_user_path %></li>
    <% end %>
  </ul>
</nav>

<!-- Problems:

Destroy account is a night mare

 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShare</title>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif|Titillium+Web' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %> 

app/views/shared/_header.html.erb
<h1><%= 'Photo Share' %> <%=" | #{title}"%></h1>

<%= render 'layouts/flash' %>

app/views/users/edit.html.erb
<%= render 'shared/header', title: "Edit Your Account" %>

<%= bootstrap_form_for(@user) do |f| %>
  <%=f.text_field :email %>
  <%=f.password_field :password %>
  <%=f.password_field :password_confirmation %>
  <%= f.file_field :avatar %>
  <%=f.submit "Edit" %>
<%end%>

<% if @user.avatar.exists? %>
  <%= link_to "Delete Avatar", user_avatar_path(@user), data: { method: :delete } %>
<% end %>


<%= link_to "Delete Account", user_path(@user),
                              data: {confirm: "Are you sure? Your account will be permanently deleted.",
                                method: :delete} %>

app/views/users/new.html.erb
<%= render 'shared/header', title: "Sign up" %>

<%= bootstrap_form_for(@user) do |f| %>
<%=f.text_field :email %>
<%=f.password_field :password %>
<%=f.password_field :password_confirmation %>
<%= f.file_field :avatar %>
<%=f.submit "Create Account" %>
<%end%>

app/views/users/show.html.erb
<%= render 'shared/header', title: @user.email %>

<%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %>